add scaffold cart
interglobalvision/ketvoid-com pull request #7
Opened 2016-09-26 19:45 UTC by mixcas

2016-09-28 17:25 UTC, mikeyrayvon commented on page-cart.php
> +    <article class="col col12 u-alert"><?php _e('Sorry, no page matched your criteria :{'); ?></article>
these classes dont exist in the new grid, ma dude

2016-09-28 17:25 UTC, mikeyrayvon reviewed
fix grid classes

2016-09-28 17:26 UTC, mikeyrayvon requested changes
fix grid classes

2016-10-05 17:20 UTC, mixcas commented
i dont undesrtand this review stuff, but i fixed it

2016-10-05 17:29 UTC, varffs commented
Mikey requested changes so he has to mark that they are acceptable before the review turns green (but seems like it can be merged anyhow, that might be a setting we need to update)

2016-10-10 22:42 UTC, merged